In [140]:
import os
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, StratifiedGroupKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

In [141]:

def lire_base_met(methode):
    X = []
    y = []
    chemin_dossier="./"
    for fichier in sorted(os.listdir(chemin_dossier)):
        if not fichier.lower().endswith(methode.lower()):
            continue
        if not fichier.lower().startswith("s"):
            continue
        
        # Normalisation du nom : on met tout en majuscules
        fichier_upper = fichier.upper()
        
        try:
            classe = int(fichier_upper[1:3])  # Sxx
        except ValueError:
            continue  # Ignore les fichiers non conformes

        chemin_fichier = os.path.join(chemin_dossier, fichier)
        with open(chemin_fichier, "r") as f:
            contenu = f.read().strip()
            valeurs = np.fromstring(contenu, sep=" ")
            X.append(valeurs)
            y.append(classe)

    return np.array(X), np.array(y)


In [151]:
methode = input("Donner une méthode")
X, y = lire_base_met(methode)
print("Dimensions :", X_GFD.shape)

Donner une méthode F2


Dimensions : (99, 100)


In [1]:

''' Approche du plus proche voisin knn'''
# Division des données 70% entrainement et 30% test 
'''
random_state => assure une division toujours identique
stratify => garantit que toutes les classes sont représentées dans train ET test
'''
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3, 
    random_state=0, 
    stratify=y
)
# Normalisation des données 
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

# Recherche du meilleur k
meilleur_k = 1
meilleurScore = -1

for k in range(1, 16):
    model = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(model, X_train_std, y_train, cv=5)
    acc = scores.mean()

    if acc > meilleurScore:
        meilleurScore = acc
        meilleur_k = k

print("Meilleur k =", meilleur_k, "avec score =", meilleurScore)

# Entraînement du modèle final avec le meilleur k
knn = KNeighborsClassifier(n_neighbors=meilleur_k, metric='euclidean')
knn.fit(X_train_std, y_train)


NameError: name 'train_test_split' is not defined

In [123]:
y_pred = knn.predict(X_test)

acc = accuracy_score(y_test, y_pred)
matrice = confusion_matrix(y_test, y_pred)
rapport = classification_report(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
print(f"Le meilleur k = {meilleur_k}\n")
print("="*50)
print(f"Accuracy: {acc:.3f}\n")
print("="*50)
print("Matrice de confusion:\n",matrice)
print("="*50)
print("Rapport de classification:\n",rapport)
print("="*50)
print(f"F-mesure: {f1:.3f}")
print("="*50)

Le meilleur k = 1

Accuracy: 0.167

Matrice de confusion:
 [[0 0 4 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 0 0]
 [0 0 1 2 0 0 1 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 2 0 0 0 1 0 0]]
Rapport de classification:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         3
           3       0.00      0.00      0.00         3
           4       1.00      0.50      0.67         4
           5       0.00      0.00      0.00         3
           6       0.00      0.00      0.00         4
           7       0.38      1.00      0.55         3
           8       0.00      0.00      0.00         3
           9       0.00      0.00      0.00         3

    accuracy                           0.17        30
   macro avg       0.15      0.17      0.13        30
weighted avg       0.17      0.17      0.14        30

F-mesure: 0.143


C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
